apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-python.fullname" . }}
  labels:
    app: {{ include "hello-python.name" . }}
    chart: {{ include "hello-python.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "hello-python.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
